from openai import OpenAI
import json
from custom_tools.current_weather import get_current_weather
from tools import tools
from typing import Any


client = OpenAI()
conversation = client.conversations.create()

instructions = """
You are a personal math tutor. When asked a math question, 
write and run code using the python tool to answer the question.
"""


def create_vector_store(name: str = "Support FAQ"):
    return client.vector_stores.create(name=name)

def basic_chat_open_ai(chat:str):
    response = client.responses.create(
        model="gpt-5-nano",
        input=[{"role": "user", "content":chat}],
        conversation=conversation.id
    )
    return response.output_text


def basic_chat_open_ai_file_search(chat: str, context: str | None = None):
    if context:
        input_msgs = [
            {
                "role": "system",
                "content": "Use the context below to answer the user's question.",
            },
            {"role": "user", "content": f"Question: {chat}\nContext: {context}"},
        ]
    else:
        input_msgs = [
            {"role": "user", "content": chat}
        ]
    response = client.responses.create(
        model="gpt-5-nano",
        input=input_msgs, # type: ignore
        conversation=conversation.id,
        instructions=instructions,
    )
    return response.output_text


def basic_chat_open_ai_with_function_calling(chat: str):
    input_list: Any = [{"role": "user", "content": chat}]
    response = client.responses.create(
        model="gpt-5-nano",
        input=input_list,
        tools=tools,  # type:ignore
        conversation=conversation.id,
        instructions=instructions,
    )
    input_list.extend(response.output)
    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_current_weather":
                weather = get_current_weather(json.loads(item.arguments))

            # 4. Provide function call results to the model
            input_list.append(
                {
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({"weather": weather}),  # type: ignore
                }
            )
    response = client.responses.create(
        model="gpt-5",
        instructions="Respond only with a horoscope generated by a tool.",
        tools=tools,  # type: ignore
        input=input_list,
    )
    return response.output_text


def streamed_chat(chat: str):
    stream = client.responses.create(
        model="gpt-5",
        input=[{"role": "user", "content": chat}],
        reasoning={"effort": "low", "summary": "auto"},
        conversation=conversation.id,
        tools=[
            {"type": "web_search"},
            {"type": "code_interpreter", "container": {"type": "auto"}},
        ],
        stream=True,
        max_output_tokens=300,
    )
    return stream


def resonining_from_openai(chat: str):
    stream = client.responses.create(
        model="gpt-5-nano",
        reasoning={"effort": "low", "summary": "auto"},
        input=[{"role": "user", "content": chat}],
        tools=[
            {"type": "web_search"},
            {"type": "code_interpreter", "container": {"type": "auto"}},
        ],
        conversation=conversation.id,
        stream=True,
        max_output_tokens=300,
    )
    return stream


def upload_file_to_vector_store(file_path: str, vector_store_name: str = "Support FAQ"):
    vector_store = create_vector_store(name=vector_store_name)
    with open(file_path, "rb") as f:
        client.vector_stores.files.upload_and_poll( 
            vector_store_id=vector_store.id, file=f
        )
    return vector_store.id


def search_vector_store(user_query: str, vector_store_id: str):
    print(user_query, vector_store_id)
    results = client.vector_stores.search(
        vector_store_id=vector_store_id,
        query=user_query,
    )
    print(results)
    return results
