
from openai import OpenAI
import json
from custom_tools.current_weather import get_current_weather
from backend.tools import tools
from typing import Any


client = OpenAI()
conversation = client.conversations.create()

instructions = """
You are a personal math tutor. When asked a math question, 
write and run code using the python tool to answer the question.
"""


def basic_chat_open_ai(chat: str):
    input_list: Any = [{"role": "user", "content": chat}]
    response = client.responses.create(
        model="gpt-5-nano",
        input=input_list,
        tools=tools,  # type:ignore
        conversation=conversation.id,
        instructions=instructions,
    )
    input_list.extend(response.output)
    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_current_weather":
                weather = get_current_weather(json.loads(item.arguments))
                print(f"Weather tool called with: {item.arguments}, result: {weather}", file=sys.stderr, flush=True)

            # 4. Provide function call results to the model
            input_list.append(
                {
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({"weather": weather}), # type: ignore
                }
            )
    response = client.responses.create(
                model="gpt-5",
                instructions="Respond only with a horoscope generated by a tool.",
                tools=tools, # type: ignore
                input=input_list,
            )
    return response.output_text


def streamed_chat(chat: str):
    stream = client.responses.create(
        model="gpt-5",
        input=[{"role": "user", "content": chat}],
        reasoning={"effort": "low", "summary": "auto"},
        conversation=conversation.id,
        tools=[
            {"type": "web_search"},
            {"type": "code_interpreter", "container": {"type": "auto"}},
        ],
        stream=True,
        max_output_tokens=300,
    )
    return stream


def resonining_from_openai(chat: str):
    stream = client.responses.create(
        model="gpt-5",
        reasoning={"effort": "low", "summary": "auto"},
        input=[{"role": "user", "content": chat}],
        tools=[
            {"type": "web_search"},
            {"type": "code_interpreter", "container": {"type": "auto"}},
        ],
        conversation=conversation.id,
        stream=True,
        max_output_tokens=300,
    )
    return stream
